//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public compra()
        {
            this.detalle_compra = new HashSet<detalle_compra>();
        }
    
        public int id { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Total { get; set; }
        public int Usuario_id { get; set; }
        public int Proveedor_id { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<detalle_compra> detalle_compra { get; set; }
    }
}
