//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbgastroclinicaEntities : DbContext
    {
        public dbgastroclinicaEntities()
            : base("name=dbgastroclinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categorias { get; set; }
        public DbSet<cliente> clientes { get; set; }
        public DbSet<compra> compras { get; set; }
        public DbSet<detalle_compra> detalle_compra { get; set; }
        public DbSet<detalle_factura> detalle_factura { get; set; }
        public DbSet<empleado> empleadoes { get; set; }
        public DbSet<factura> facturas { get; set; }
        public DbSet<lote> lotes { get; set; }
        public DbSet<permiso> permisoes { get; set; }
        public DbSet<permiso_usuario> permiso_usuario { get; set; }
        public DbSet<presentacion> presentacions { get; set; }
        public DbSet<producto> productoes { get; set; }
        public DbSet<producto_categoria> producto_categoria { get; set; }
        public DbSet<producto_presentacion> producto_presentacion { get; set; }
        public DbSet<proveedor> proveedors { get; set; }
        public DbSet<tbl_detalle_fact> tbl_detalle_fact { get; set; }
        public DbSet<telefono> telefonoes { get; set; }
        public DbSet<tipo_telefono> tipo_telefono { get; set; }
        public DbSet<tipo_usuario> tipo_usuario { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
