//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_compra
    {
        public int id { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public int Compra_id { get; set; }
        public int Lote_id { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual lote lote { get; set; }
    }
}
