//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.telefonoes = new HashSet<telefono>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Direccion { get; set; }
        public string NIT { get; set; }
        public string DPI { get; set; }
        public Nullable<double> Sueldo { get; set; }
    
        public virtual ICollection<telefono> telefonoes { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
