//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Serie { get; set; }
        public int Cliente_id { get; set; }
        public int Usuario_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
