//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.producto_categoria = new HashSet<producto_categoria>();
            this.producto_presentacion = new HashSet<producto_presentacion>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Fabricante { get; set; }
    
        public virtual ICollection<producto_categoria> producto_categoria { get; set; }
        public virtual ICollection<producto_presentacion> producto_presentacion { get; set; }
    }
}
