//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_categoria
    {
        public int id { get; set; }
        public int Categoria_id { get; set; }
        public int Producto_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual producto producto { get; set; }
    }
}
