//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.compras = new HashSet<compra>();
            this.telefonoes = new HashSet<telefono>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string NIF { get; set; }
        public string DPI { get; set; }
    
        public virtual ICollection<compra> compras { get; set; }
        public virtual ICollection<telefono> telefonoes { get; set; }
    }
}
