//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalle_fact
    {
        public int idtbl_Detalle_fact { get; set; }
        public string subTotal { get; set; }
        public string cantidad { get; set; }
    }
}
