//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_usuario
    {
        public tipo_usuario()
        {
            this.permiso_usuario = new HashSet<permiso_usuario>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<permiso_usuario> permiso_usuario { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
