//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.producto_categoria = new HashSet<producto_categoria>();
        }
    
        public int id { get; set; }
        public string Categoria1 { get; set; }
    
        public virtual ICollection<producto_categoria> producto_categoria { get; set; }
    }
}
