//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        public lote()
        {
            this.detalle_compra = new HashSet<detalle_compra>();
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int id { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public Nullable<int> Existencias { get; set; }
        public Nullable<double> Costo { get; set; }
        public int Producto_Presentacion_id { get; set; }
    
        public virtual ICollection<detalle_compra> detalle_compra { get; set; }
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual producto_presentacion producto_presentacion { get; set; }
    }
}
