//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public permiso()
        {
            this.permiso_usuario = new HashSet<permiso_usuario>();
        }
    
        public int id { get; set; }
        public string Modulo { get; set; }
    
        public virtual ICollection<permiso_usuario> permiso_usuario { get; set; }
    }
}
