//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso_usuario
    {
        public int id { get; set; }
        public int Tipo_Usuario_id { get; set; }
        public int Permiso_id { get; set; }
    
        public virtual permiso permiso { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
