//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class presentacion
    {
        public presentacion()
        {
            this.producto_presentacion = new HashSet<producto_presentacion>();
        }
    
        public int id { get; set; }
        public string Presentacion1 { get; set; }
    
        public virtual ICollection<producto_presentacion> producto_presentacion { get; set; }
    }
}
