//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_presentacion
    {
        public producto_presentacion()
        {
            this.lotes = new HashSet<lote>();
        }
    
        public int id { get; set; }
        public int Producto_id { get; set; }
        public int Presentacion_id { get; set; }
        public Nullable<int> Existencia_Total { get; set; }
        public Nullable<double> Precio_Venta { get; set; }
    
        public virtual ICollection<lote> lotes { get; set; }
        public virtual presentacion presentacion { get; set; }
        public virtual producto producto { get; set; }
    }
}
