//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGastro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.compras = new HashSet<compra>();
            this.facturas = new HashSet<factura>();
        }
    
        public int id { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public int Empleado_id { get; set; }
        public int Tipo_Usuario_id { get; set; }
    
        public virtual ICollection<compra> compras { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<factura> facturas { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
